### ISSUE TITLE
Chinese characters appear garbled

### ISSUE THREAD

**Issue by dasu88** [kdalanon/ChatGPT-AutoHotkey-Utility#1]
When I use this AHK script, if the returned string contains Chinese characters, they appear as garbled text. I hope to find a solution to this issue.

**Comment by kdalanon** [comment]
Hello, this issue was resolved in the v1.1.2 release.

**Comment by dasu88** [comment]
> Hello, this is now fixed as of v1.1.2.

Thank you for providing such a great tool.

**Comment by kdalanon** [comment]
Hi @dasu88 ,

Thank you for using and supporting my app!

I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch.  It offers the same core features, but with the addition of the following:
- Type custom prompts manually
- Interactive Response Window - Chat, Copy, Retry, and see Chat History
- Auto-Paste functionality
- Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
- Sending message to multiple models at the same time
- Web search  

For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).

**Comment by dasu88** [comment]
> Hi [@dasu88](https://github.com/dasu88) ,
> 
> Thank you for using and supporting my app!
> 
> I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch. It offers the same core features, but with the addition of the following:
> 
> * Type custom prompts manually
> * Interactive Response Window - Chat, Copy, Retry, and see Chat History
> * Auto-Paste functionality
> * Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
> * Sending message to multiple models at the same time
> * Web search
> 
> For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).

Thank you for your notification. I will continue to follow the new project, but I tried it, and the new project kept having errors after running it. I haven't been able to use it successfully so far.

**Comment by kdalanon** [comment]
> > Hi [@dasu88](https://github.com/dasu88) ,
> > Thank you for using and supporting my app!
> > I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch. It offers the same core features, but with the addition of the following:
> > 
> > * Type custom prompts manually
> > * Interactive Response Window - Chat, Copy, Retry, and see Chat History
> > * Auto-Paste functionality
> > * Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
> > * Sending message to multiple models at the same time
> > * Web search
> > 
> > For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).
> 
> Thank you for your notification. I will continue to follow the new project, but I tried it, and the new project kept having errors after running it. I haven't been able to use it successfully so far.

Hello! Open a new issue on the new project page and explain the details of the issue, and I will take a look!
