### ISSUE TITLE
Request for V1 Support

### ISSUE THREAD

**Issue by semeerwork** [kdalanon/ChatGPT-AutoHotkey-Utility#17]
I really want to use this script at work. but our systems are pre-installed with V1 and we can’t upgrade to V2 due to admin access restrictions and frequent system changes in my workspace(due to shift). Could you please consider adding support for V1?

**Comment by kdalanon** [comment]
Hi! May I ask if you've already tried the following:

1. Download AHK v2 zip from [their website.](https://www.autohotkey.com/download/ahk-v2.zip)
2. Extract the exe

![image](https://github.com/user-attachments/assets/9cee985b-a7f3-4a74-9398-0d79b9f73b65)

3. Right-click the .ahk script ➡ Open with ➡ Choose another app ➡ More apps ➡ Look for another app on this PC

![image](https://github.com/user-attachments/assets/fe53a3e5-a972-4086-8167-b22b8cebc54d)

![image](https://github.com/user-attachments/assets/cb986134-67ff-4711-a47a-b68f8370d753)

4. Select the AHK exe

![image](https://github.com/user-attachments/assets/cd89da12-51b7-493c-87e7-3dcb69c760a0)

This setup doesn't require you to install AHK, eliminating the need for admin access.
