### ISSUE TITLE
Sometimes need to reload

### ISSUE THREAD

**Issue by josegemez** [kdalanon/ChatGPT-AutoHotkey-Utility#2]
Hi! 
Occasionally, the script hangs and requires a reload. I resolve this by performing a force reload in the close button, and it effectively resolves the issue for me.

**Comment by josegemez** [comment]
Close(*) {
    HTTP_Request.Abort
    Response_Window.Hide
    global Response_Window_Status := "Cerrar"
    reload
}

**Comment by kdalanon** [comment]
Hi @josegemez ,

Thank you for using and supporting my app!

I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch.  It offers the same core features, but with the addition of the following:
- Type custom prompts manually
- Interactive Response Window - Chat, Copy, Retry, and see Chat History
- Auto-Paste functionality
- Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
- Sending message to multiple models at the same time
- Web search  

For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).
