### ISSUE TITLE
two small feature requests

### ISSUE THREAD

**Issue by michaelbeijer** [kdalanon/ChatGPT-AutoHotkey-Utility#3]
Hi there! Thanks for the great little app!

Is there any way to do this:

1. Have the text generated/translated by ChatGPT automatically copied to my clipboard?
2. Close the pop-up window with the Escape key?

**Comment by michaelbeijer** [comment]
OK, I solved #2:

```
/*
====================================================
Hotkey
====================================================
*/

`::MenuPopup.Show()

; Close the response window when the Escape key is pressed
Escape::Close()
```

**Comment by michaelbeijer** [comment]
solved #1 as well. I added the bold bit to the code:

...
try {
    if (HTTP_Request.status == 200) {
        ...
        JSON_Response := var.Get("choices")[1].Get("message").Get("content")
        RetryButton.Enabled := 1
        CopyButton.Enabled := 1
        Response.Value := JSON_Response

        **; Automatically copy the response to the clipboard
        A_Clipboard := JSON_Response**

        ...
    } else {
        ...
    }
}
...

**Comment by michaelbeijer** [comment]
in the end, it turns out I didn't need: `Escape::Close()` to close the menu. 

Pressing Esc closes it even without `Escape::Close()`

**Comment by kdalanon** [comment]
Hi @michaelbeijer ,

Thank you for using and supporting my app!

I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch.  It offers the same core features, but with the addition of the following:
- Type custom prompts manually
- Interactive Response Window - Chat, Copy, Retry, and see Chat History
- Auto-Paste functionality
- Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
- Sending message to multiple models at the same time
- Web search  

For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).
