### ISSUE TITLE
i18n-Chinese

### ISSUE THREAD

**Issue by publieople** [kdalanon/ChatGPT-AutoHotkey-Utility#5]
Thank you for creating this script. It has been of great help to my learning and work.
I am Chinese, so I have changed the text content of the script to Chinese when using it.  [here](https://github.com/publieople/ChatGPT-AutoHotkey-Utility-cn)
I hope it can benefit more people.
感谢您制作此脚本,它给我的学习和工作带来了很大帮助.
我是中国人,所以我使用时将脚本的文本内容改为了中文.[这里](https://github.com/publieople/ChatGPT-AutoHotkey-Utility-cn])
希望能让更多人受益

**Comment by kdalanon** [comment]
Hi @publieople ,

Thank you for using and supporting my app!

I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch.  It offers the same core features, but with the addition of the following:
- Type custom prompts manually
- Interactive Response Window - Chat, Copy, Retry, and see Chat History
- Auto-Paste functionality
- Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
- Sending message to multiple models at the same time
- Web search  

For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).
