### ISSUE TITLE
Issue with JSON escaping

### ISSUE THREAD

**Issue by angeloprado** [kdalanon/ChatGPT-AutoHotkey-Utility#7]
For certain text, JSON escaping functionality fails.

Please consider updating ProcessRequest as follows:
```

/*
====================================================
Connect to ChatGPT API and process request
====================================================
*/

ProcessRequest(ChatGPT_Prompt, Status_Message, API_Model, Retry_Status) {
    if (Retry_Status != "Retry") {
        A_Clipboard := ""
        Send "^c"
        if !ClipWait(2) {
            MsgBox "The attempt to copy text onto the clipboard failed."
            return
        }
        CopiedText := A_Clipboard
        ChatGPT_Prompt := ChatGPT_Prompt "`n`n" CopiedText
        ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, '(\\|")+', '\$1') ; Clean back spaces and quotes
        ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, "`n", "\n") ; Clean newlines
        ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, "`r", "") ; Remove carriage returns
        global Previous_ChatGPT_Prompt := ChatGPT_Prompt
        global Previous_Status_Message := Status_Message
        global Previous_API_Model := API_Model
        global Response_Window_Status
    }

    OnMessage 0x200, WM_MOUSEHOVER
    Response.Value := Status_Message
    if (Response_Window_Status = "Closed") {
        Response_Window.Show("AutoSize Center")
        Response_Window_Status := "Open"
        RetryButton.Enabled := 0
        CopyButton.Enabled := 0
    }    
    DllCall("SetFocus", "Ptr", 0)

    global HTTP_Request := ComObject("WinHttp.WinHttpRequest.5.1")
    HTTP_Request.open("POST", API_URL, true)
    HTTP_Request.SetRequestHeader("Content-Type", "application/json")
    HTTP_Request.SetRequestHeader("Authorization", "Bearer " API_Key)
    Messages := '{ "role": "user", "content": "' ChatGPT_Prompt '" }'
    JSON_Request := '{ "model": "' API_Model '", "messages": [' Messages '] }'
    HTTP_Request.SetTimeouts(60000, 60000, 60000, 60000)
    HTTP_Request.Send(JSON_Request)
    SetTimer LoadingCursor, 1
    if WinExist("Response") {
        WinActivate "Response"
    }
    HTTP_Request.WaitForResponse
    try {
        if (HTTP_Request.status == 200) {
            SafeArray := HTTP_Request.responseBody
	    pData := NumGet(ComObjValue(SafeArray) + 8 + A_PtrSize, 'Ptr')
	    length := SafeArray.MaxIndex() + 1
	    JSON_Response := StrGet(pData, length, 'UTF-8')
            var := Jxon_Load(&JSON_Response)
            JSON_Response := var.Get("choices")[1].Get("message").Get("content")
            RetryButton.Enabled := 1
            CopyButton.Enabled := 1
            Response.Value := JSON_Response

            SetTimer LoadingCursor, 0
            OnMessage 0x200, WM_MOUSEHOVER, 0
            Cursor := DllCall("LoadCursor", "uint", 0, "uint", 32512) ; Arrow cursor
            DllCall("SetCursor", "UPtr", Cursor)

            Response_Window.Flash()
            DllCall("SetFocus", "Ptr", 0)
        } else {
            RetryButton.Enabled := 1
            CopyButton.Enabled := 1
            Response.Value := "Status " HTTP_Request.status " " HTTP_Request.responseText

            SetTimer LoadingCursor, 0
            OnMessage 0x200, WM_MOUSEHOVER, 0
            Cursor := DllCall("LoadCursor", "uint", 0, "uint", 32512) ; Arrow cursor
            DllCall("SetCursor", "UPtr", Cursor)

            Response_Window.Flash()
            DllCall("SetFocus", "Ptr", 0)
        }
    }
}


```

**Comment by kdalanon** [comment]
Will update this when I have time.

**Comment by kdalanon** [comment]
May I ask what lines need to be changed? I've diff them and there seems to be no change: https://www.diffchecker.com/PWgCfXS3/

**Comment by angeloprado** [comment]
Hi @kdalanon , I must have pasted the wrong code. 

1. Remove the following lines: 
   **ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, '(\\|")+', '\$1') ; Clean back spaces and quotes
        ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, "`n", "\n") ; Clean newlines
        ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, "`r", "") ; Remove carriage returns**

2. Replace this: 
**Messages := '{ "role": "user", "content": "' ChatGPT_Prompt '" }'
    JSON_Request := '{ "model": "' API_Model '", "messages": [' Messages '] }'**

With:
**Messages := Map("role", "user", "content", ChatGPT_Prompt)
    JSON_Request := Map("model", API_Model, "messages", [Messages])
    JSON_Request := Jxon_Dump(JSON_Request)**

3. Lastly, for usabilty consder adding this after  _JSON_Response := var.Get("choices")[1].Get("message").Get("content")_:
   ; Replace newlines with carriage return and line feed
    JSON_Response := StrReplace(JSON_Response, "\n", "`r`n")

**Comment by angeloprado** [comment]
@kdalanon  here we go https://www.diffchecker.com/lW1zuGOh/

**Comment by angeloprado** [comment]
The relevant changes for you would be lines 185 and 208. Feel free to incorporate the other suggestions

**Comment by kdalanon** [comment]
> The relevant changes for you would be lines 185 and 208. Feel free to incorporate the other suggestions

Thank you. I am now incorporating your suggestions. Can you provide some texts where JSON escaping functionality fails, so that I can test if the revised code is working?

**Comment by Avastgard** [comment]
Might want to include `ChatGPT_Prompt := RegExReplace(ChatGPT_Prompt, "\t", "") ; Remove horizontal tabs` to remove horizontal tabs. This is useful if you select text from a numbered list in Microsoft Word (my use case most of the time).

**Comment by kdalanon** [comment]
Hi @angeloprado ,

Thank you for using and supporting my app!

I will be archiving this repository sometime next month as I've created a significantly improved version of this application, rebuilt from scratch.  It offers the same core features, but with the addition of the following:
- Type custom prompts manually
- Interactive Response Window - Chat, Copy, Retry, and see Chat History
- Auto-Paste functionality
- Multi-model support that utilizes [OpenRouter.ai](https://openrouter.ai/), not just ChatGPT
- Sending message to multiple models at the same time
- Web search  

For ongoing development, bug fixes, and the best experience, please switch to the new app: [LLM AutoHotkey Assistant](https://github.com/kdalanon/LLM-AutoHotkey-Assistant).
